name: CI/CD for Docker CI Test Express App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install Dependencies
        run: npm ci

      - name: Build & Push Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/docker-ci-test:latest .
          docker push "${{ secrets.DOCKER_USERNAME }}"/docker-ci-test:latest
